#!/bin/bash
# source key change for doro67
# https://itectec.com/ubuntu/ubuntu-how-to-automatically-change-the-system-keyboard-layout-when-plugging-in-an-external-keyboard/
sleep 1

DISPLAY=":0.0"
HOME=/home/ianfundere
XAUTHORITY=$HOME/.Xauthority
export DISPLAY XAUTHORITY HOME

remote_id=$(
    xinput list |
        grep -Ev 'Control' |
        sed -n 's/.*Backprop Studio Doro67 Multi PCB*.*id=\([0-9]*\).*keyboard.*/\1/p'
)
[ "$remote_id" ] || exit

mkdir -p /tmp/xkb/symbols

cat >/tmp/xkb/symbols/custom_doro <<\EOF

xkb_symbols "remote" {
    key <CAPS> { [ Super_L ] };
};
EOF

setxkbmap -device $remote_id -print |
    sed 's/\(xkb_symbols.*\)"/\1+custom_doro(remote)"/' |
    xkbcomp -I/tmp/xkb -i $remote_id -synch - $DISPLAY 2>/dev/null
