#!/bin/bash
sleep 1
DISPLAY=":0.0"
HOME=/home/$USER/
XAUTHORITY=$HOME/.Xauthority        # if you use GDM, try /run/user/1000/gdm/Xauthority here
export DISPLAY XAUTHORITY HOME
KEYBOARDID=$(cat $HOME/.keyboardid)
/usr/bin/xinput reattach $KEYBOARDID 3

